# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: startup
    init: |
      echo 'init script' # runs during prebuild
      cp .env.example .env # pre-copy the .env
    command: |
      open .env # open .env ready for editing
